// QuoteForge
// Generate a working single-file internal tool from a plain description.
// Runs fully offline: a deterministic template engine extracts a likely
// entity + fields from the description and renders a complete CRUD app
// (form, filterable table, localStorage). No LLM key required.
//
// If OPENROUTER_API_KEY is set, the field extraction can be enhanced by the
// model. The template path still works with no key. That is the default demo.
//
// Run:
//   npm install
//   npm start
//   open http://localhost:3000

const express = require("express");
const path = require("path");
const fs = require("fs");

const PORT = 3001;
const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

const STOPWORDS = new Set([
  "a", "an", "the", "form", "to", "for", "of", "and", "with", "that", "show",
  "them", "in", "on", "at", "by", "log", "track", "manage", "create", "add",
  "list", "app", "tool", "internal", "simple", "small", "build", "me",
]);

// Guess an entity name + field names from a description, no ML needed.
function extractSpec(description) {
  const text = description.toLowerCase();
  const words = text
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w && !STOPWORDS.has(w));

  // entity: first noun-ish word, singularized roughly
  let entity = words[0] || "item";
  entity = entity.replace(/s$/, "");

  // fields: look for "with <field>, <field> and <field>" or "by <field>"
  const fieldHits = [];
  const patterns = [
    /(?:with|fields?|columns?|by)\s+([a-z0-9 ,]+?)(?:\.|\band\b|$)/g,
  ];
  for (const p of patterns) {
    let m;
    while ((m = p.exec(text)) !== null) {
      m[1]
        .split(/,| and /)
        .map((s) => s.trim())
        .filter(Boolean)
        .forEach((f) => fieldHits.push(f));
    }
  }
  let fields = [...new Set(fieldHits)].slice(0, 6);
  if (fields.length === 0) {
    // fall back to a few content words after the entity
    fields = words.slice(1, 4).concat(["notes", "date"]);
  }
  fields = fields.map((f) => f.replace(/[^a-z0-9]/g, "_")).filter(Boolean);

  const label = entity.charAt(0).toUpperCase() + entity.slice(1);
  const fieldDefs = fields.map((f) => ({
    key: f,
    label: f.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
  }));
  return { entity, label, fields: fieldDefs };
}

function renderApp(spec) {
  const cols = spec.fields
    .map(
      (f) =>
        `      <th>${f.label}</th>`
    )
    .join("\n");
  const inputs = spec.fields
    .map(
      (f) =>
        `        <input id="f_${f.key}" placeholder="${f.label}" />`
    )
    .join("\n");
  const cells = spec.fields
    .map((f) => `          <td>\${r.${f.key} || ""}</td>`)
    .join("\n");
  const adds = spec.fields
    .map((f) => `    obj.${f.key} = document.getElementById("f_${f.key}").value;`)
    .join("\n");
  const filters = spec.fields
    .map(
      (f) =>
        `      if (q && !String(r.${f.key}).toLowerCase().includes(q)) return false;`
    )
    .join("\n");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${spec.label} Tracker</title>
<style>
:root{--bg:#0d0d0f;--panel:#15151a;--ink:#f3f2ec;--dim:#9a9a92;--lime:#c6ff00;--line:rgba(243,242,236,.14);--mono:ui-monospace,Menlo,Consolas,monospace}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--ink);font-family:var(--mono);padding:32px;line-height:1.5}
h1{font-size:26px;letter-spacing:-.02em} h1 b{color:var(--lime)}
.sub{color:var(--dim);margin:6px 0 22px;font-size:13px}
form{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px}
input{background:var(--panel);border:1px solid var(--line);color:var(--ink);padding:10px;font-family:var(--mono);font-size:13px;min-width:160px}
input:focus{outline:none;border-color:var(--lime)}
button{background:var(--lime);color:#000;border:0;padding:10px 16px;font-family:var(--mono);font-weight:700;cursor:pointer}
.search{margin-bottom:16px}
table{width:100%;border-collapse:collapse;font-size:13px}
th,td{text-align:left;padding:10px 12px;border-bottom:1px solid var(--line)}
th{color:var(--dim);text-transform:uppercase;font-size:11px;letter-spacing:.06em}
.cnt{color:var(--dim);font-size:12px;margin-bottom:10px}
</style></head>
<body>
<h1>${spec.label} <b>Tracker</b></h1>
<div class="sub">Generated by QuoteForge. Saved in your browser (localStorage).</div>
<form id="frm">
${inputs}
  <button type="submit">Add</button>
</form>
<input class="search" id="q" placeholder="Search..." style="width:100%;background:var(--panel);border:1px solid var(--line);color:var(--ink);padding:10px;font-family:var(--mono)" />
<div class="cnt" id="cnt"></div>
<table><thead><tr><th>#</th>${cols}<th></th></tr></thead><tbody id="tb"></tbody></table>
<script>
const KEY="${spec.entity}_records";
let recs = JSON.parse(localStorage.getItem(KEY) || "[]");
function save(){ localStorage.setItem(KEY, JSON.stringify(recs)); render(); }
document.getElementById("frm").onsubmit = (e)=>{
  e.preventDefault();
  const obj = { id: Date.now() };
${adds}
  recs.push(obj); save();
  e.target.reset();
};
document.getElementById("q").oninput = render;
function del(id){ recs = recs.filter(r=>r.id!==id); save(); }
function render(){
  const q = document.getElementById("q").value.toLowerCase();
  const tb = document.getElementById("tb"); tb.innerHTML="";
  const list = recs.filter(r=>{
${filters}
    return true;
  });
  list.forEach((r,i)=>{
    const tr = document.createElement("tr");
    tr.innerHTML = '<td>'+(i+1)+'</td>${cells}<td><button onclick="del('+r.id+')" style="padding:4px 8px;font-size:11px">x</button></td>';
    tb.appendChild(tr);
  });
  document.getElementById("cnt").textContent = list.length + " record(s)";
}
render();
</script>
</body></html>`;
}

app.post("/api/generate", (req, res) => {
  const description = (req.body.description || "").toString();
  if (!description.trim()) return res.status(400).json({ error: "no description" });
  const spec = extractSpec(description);
  const html = renderApp(spec);
  res.json({ spec, html });
});

app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

app.listen(PORT, () => console.log(`QuoteForge on http://localhost:${PORT}`));
